### ISSUE TITLE
exception

### ISSUE THREAD

**Issue by likezjuisee** [pebbe/zmq4#102]
Could you help me to find the reason of this corruption?

2017/05/15 13:22:44 [DEBUG]  [/home/like/project/goadbserver/src/adbservice/adbservice.go 70]  O A_OKAY message
Resource temporarily unavailable (src/signaler.cpp:282)
SIGABRT: abort
PC=0x7f6e54388428 m=15 sigcode=18446744073709551610
signal arrived during cgo execution

goroutine 51 [syscall, locked to thread]:
runtime.cgocall(0x5154a0, 0xc420042c10, 0xc42041a320)
        /home/like/install/go/src/runtime/cgocall.go:131 +0xe2 fp=0xc420042bc0 sp=0xc420042b80
github.com/pebbe/zmq4._C2func_zmq_send(0x7f6e44003210, 0xc420423b20, 0x14, 0x2, 0x0, 0x0, 0x0)
        github.com/pebbe/zmq4/_obj/_cgo_gotypes.go:484 +0x6e fp=0xc420042c10 sp=0xc420042bc0
github.com/pebbe/zmq4.(*Socket).SendBytes.func1(0xc420423b20, 0x14, 0x14, 0x7f6e44003210, 0xc420423b20, 0x14, 0x7f6e00000002, 0x153, 0x0, 0x0)
        /home/like/go/src/github.com/pebbe/zmq4/zmq4.go:870 +0x13d fp=0xc420042c78 sp=0xc420042c10
github.com/pebbe/zmq4.(*Socket).SendBytes(0xc42001a9f0, 0xc420423b20, 0x14, 0x14, 0x2, 0x18, 0x52e9c0, 0x7f6e54c93130)
        /home/like/go/src/github.com/pebbe/zmq4/zmq4.go:870 +0x8d fp=0xc420042ce8 sp=0xc420042c78
github.com/pebbe/zmq4.(*Socket).sendMessage(0xc42001a9f0, 0x0, 0xc420042e70, 0x2, 0x2, 0xc42041a300, 0xc420042e58, 0xc42041a300)
        /home/like/go/src/github.com/pebbe/zmq4/utils.go:89 +0x44e fp=0xc420042db0 sp=0xc420042ce8
github.com/pebbe/zmq4.(*Socket).SendMessage(0xc42001a9f0, 0xc420042e70, 0x2, 0x2, 0x9, 0x18, 0xc42041e000)
        /home/like/go/src/github.com/pebbe/zmq4/utils.go:18 +0x52 fp=0xc420042e00 sp=0xc420042db0
zmqutil.(*AgentZmqUtil).SendResponseMessageToZmq(0xc42005c1c0, 0xc42041e000, 0x117, 0x120, 0x117)
        /home/like/project/goadbserver/src/zmqutil/agentzmqutil.go:68 +0x11c fp=0xc420042ea0 sp=0xc420042e00
adbservice.(*AdbService).WriteResponse(0xc42007a100, 0xc42041e000, 0x117, 0x120, 0x1000)
        /home/like/project/goadbserver/src/adbservice/adbservice.go:162 +0x6d fp=0xc420042f18 sp=0xc420042ea0
adbservice.(*AdbService).ReadFromAdbClientToTcpConn(0xc42007a100)
        /home/like/project/goadbserver/src/adbservice/adbservice.go:141 +0x10a fp=0xc420042f98 sp=0xc420042f18
adbservice.(*AdbService).ReadFromAdbClientToTcpConnAlive(0xc42007a100)
        /home/like/project/goadbserver/src/adbservice/adbservice.go:153 +0x46 fp=0xc420042fd8 sp=0xc420042f98
runtime.goexit()
        /home/like/install/go/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc420042fe0 sp=0xc420042fd8
created by adbservice.(*AdbService).HandleOpenPacket
        /home/like/project/goadbserver/src/adbservice/adbservice.go:94 +0x2a8

goroutine 1 [IO wait, 2 minutes]:
net.runtime_pollWait(0x7f6e54d17fe0, 0x72, 0x80bf40)
        /home/like/install/go/src/runtime/netpoll.go:164 +0x59
net.(*pollDesc).wait(0xc42005c0d8, 0x72, 0x80a6c8, 0xc420422020)
        /home/like/install/go/src/net/fd_poll_runtime.go:75 +0x38
net.(*pollDesc).waitRead(0xc42005c0d8, 0xffffffffffffffff, 0x0)
        /home/like/install/go/src/net/fd_poll_runtime.go:80 +0x34
net.(*netFD).accept(0xc42005c070, 0x0, 0x80bbc0, 0xc420422020)
        /home/like/install/go/src/net/fd_unix.go:430 +0x1e5
net.(*TCPListener).accept(0xc42000e048, 0xc4200adda8, 0x513aad, 0x453610)
        /home/like/install/go/src/net/tcpsock_posix.go:136 +0x2e
net.(*TCPListener).AcceptTCP(0xc42000e048, 0x5729b0, 0xc420076600, 0x0)
        /home/like/install/go/src/net/tcpsock.go:215 +0x49
main.main()
        /home/like/project/goadbserver/src/server/server.go:97 +0x63c

goroutine 17 [syscall, 2 minutes, locked to thread]:
runtime.goexit()
        /home/like/install/go/src/runtime/asm_amd64.s:2197 +0x1

goroutine 5 [syscall, 2 minutes]:
os/signal.signal_recv(0x0)
        /home/like/install/go/src/runtime/sigqueue.go:116 +0x104
os/signal.loop()
        /home/like/install/go/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.1
        /home/like/install/go/src/os/signal/signal_unix.go:28 +0x41

goroutine 6 [select, 2 minutes, locked to thread]:
runtime.gopark(0x572f10, 0x0, 0x569ee8, 0x6, 0x18, 0x2)
        /home/like/install/go/src/runtime/proc.go:271 +0x13a
runtime.selectgoImpl(0xc42003cf50, 0x0, 0x18)
        /home/like/install/go/src/runtime/select.go:423 +0x1364
runtime.selectgo(0xc42003cf50)
        /home/like/install/go/src/runtime/select.go:238 +0x1c
runtime.ensureSigM.func1()
        /home/like/install/go/src/runtime/signal_unix.go:434 +0x2dd
runtime.goexit()
        /home/like/install/go/src/runtime/asm_amd64.s:2197 +0x1

goroutine 7 [chan receive, 2 minutes]:
main.main.func1(0xc42006c120)
        /home/like/project/goadbserver/src/server/server.go:55 +0x57
created by main.main
        /home/like/project/goadbserver/src/server/server.go:59 +0x335

goroutine 8 [runnable]:
time.Sleep(0xf4240)
        /home/like/install/go/src/runtime/time.go:59 +0xf9
handler.(*Handler).Handle(0xc42000a800)
        /home/like/project/goadbserver/src/handler/handler.go:194 +0x589
created by main.main
        /home/like/project/goadbserver/src/server/server.go:91 +0xb1b

goroutine 9 [runnable]:
time.Sleep(0x2710)
        /home/like/install/go/src/runtime/time.go:59 +0xf9
handler.(*Handler).AgentReadPacketFromZmq(0xc42000a800)
        /home/like/project/goadbserver/src/handler/handler.go:165 +0x10f
created by main.main
        /home/like/project/goadbserver/src/server/server.go:92 +0xb3d

goroutine 10 [chan send]:
zmqutil.(*AgentZmqUtil).RecvMessageFromZmq(0xc42005c1c0)
        /home/like/project/goadbserver/src/zmqutil/agentzmqutil.go:93 +0x142
created by handler.(*Handler).AgentReadPacketFromZmq
        /home/like/project/goadbserver/src/handler/handler.go:159 +0x8a

goroutine 34 [runnable]:
time.Sleep(0xf4240)
        /home/like/install/go/src/runtime/time.go:59 +0xf9
handler.(*Handler).Handle(0xc420076600)
        /home/like/project/goadbserver/src/handler/handler.go:194 +0x589
created by main.main
        /home/like/project/goadbserver/src/server/server.go:107 +0x82d

rax    0x0
rbx    0x7f6e440036d8
rcx    0x7f6e54388428
rdx    0x6
rdi    0x12ce
rsi    0x1493
rbp    0x7f6e544e2db0
rsp    0x7f6e2f7fdb18
r8     0x7f6e2f7fe700
r9     0x38
r10    0x8
r11    0x202
r12    0x7f6e2f7fdcd0
r13    0x7f6e440036d8
r14    0x2
r15    0xd1
rip    0x7f6e54388428
rflags 0x202
cs     0x33
fs     0x0
gs     0x0

**Comment by pebbe** [comment]
This is not a proper issue report.

For help with programming, please ask somewhere else.
