### ISSUE TITLE
Security support in zmq4

### ISSUE THREAD

**Issue by jay11ca39** [pebbe/zmq4#112]
Hello @pebbe,

I want to use zeroMQ for my project. My project is in go language. So, I want to use go binding for zeroMQ. 

I got to know there are 2 go bindings available:
(a) http://github.com/pebbe/zmq4
(b) https://github.com/zeromq/goczmq

Source: http://zeromq.org/bindings:go

But I have a few questions:
1. Is security feature is fully supported in this binding?
2. Is there is any performance comparison between : 
    This binding and https://github.com/zeromq/goczmq ?

It is a blocker for me, which one to choose.
can you please help me out in this.
Thanks in advance.

**Comment by pebbe** [comment]
1. Yes, I think so. See https://github.com/pebbe/zmq4/tree/master/examples_security
2. Not that I know of.

**Comment by jay11ca39** [comment]
Hi @pebbe ,

I am using this library as it is providing the simple APIs from developer point of view.
I have one question: Is zmq4 is thread safe? 
As per my understanding it is not. 
can you please tell me as you are the developer of this. 
Thanks in advance.
