### ISSUE TITLE
Is zmq4 go library is thread safe

### ISSUE THREAD

**Issue by jay11ca39** [pebbe/zmq4#115]
Hi @pebbe ,

I want to try the following scenarios:
1. One thread [go routine] continuously publishing  the event.
2. One thread can terminate the context.

Similar to above, I want to try different scenarios.
- Can you please let me know how it is being handled in zmq4 library?
- Is this library has thread-safe logic?

**Comment by omani** [comment]
zmq is not thread safe. I use different contexts when multithreading is needed and mutex them while switching between them.

**Comment by pebbe** [comment]
zmq4 is as thread safe as ZeroMQ. Context is thread safe. Most sockets are not. There are some newer socket types that are thread safe. Check the documentation for ZeroMQ.
