### ISSUE TITLE
SetRcvtimeo question

### ISSUE THREAD

**Issue by iesrbt** [pebbe/zmq4#141]
Hi,
I'm using sock.SetRcvtimeo like so (before the Connect):

zmq_sub, _ := zmq.NewSocket(zmq.SUB)
defer zmq_sub.Close()

a := zmq_sub.SetRcvtimeo(10000)
b, c := zmq_sub.GetRcvtimeo()
log.Println("=", a, b, c)

The output holds: 
= nil 0s nil
So basically no error nowhere, but timeout still being zero?
(Current 0MQ version is: 4 2 3)

And actually:  zmq_sub.RecvMessage(0) returns straight away with "resource temporarily unavailable"

What do I miss?
Thanks for helping.

**Comment by pebbe** [comment]
`SetRcvtimeo` expects a time.Duration. Your literal is interpreted as 0.01 milliseconds, but zmq doesn't handle values below 1 millisecond.

Don't use literal values. Use `5 * time.Second` or something like that.

**Comment by iesrbt** [comment]
Oh... I knew it what me ;-)
Thanks for your help.
