### ISSUE TITLE
Doesn't seem to work on MacOS

### ISSUE THREAD

**Issue by pavanagrawal123** [pebbe/zmq4#144]
```
Package libunwind was not found in the pkg-config search path.
Perhaps you should add the directory containing `libunwind.pc'
to the PKG_CONFIG_PATH environment variable
Package 'libunwind', required by 'libzmq', not found
```
Please see https://github.com/gopherdata/gophernotes/issues/157 for some more info!

**Comment by pavanagrawal123** [comment]
It doesn't seem like this is a compiled version of libunwind for MacOS. Can you point me in the right direction? I tried installing some headers from MacPorts, but it didn't seem to help.

**Comment by pebbe** [comment]
It says right there: You should add the directory containing `libunwind.pc'
to the PKG_CONFIG_PATH environment variable

This is a MacOS problem, not a zmq4 problem.
