### ISSUE TITLE
Getting "interrupted system call" (EINTR) on socket.RecvMessage()

### ISSUE THREAD

**Issue by veegee** [pebbe/zmq4#17]
This bug report is posted as recommended by the good people who have replied to my question here: https://groups.google.com/forum/#!topic/Golang-nuts/TeZwtP6z98w

socket.RecvMessage() is getting interrupted with EINTR for some reason and according to the golang-nuts replies, this should be hidden from the user and automatically retried.

**Comment by rightfold** [comment]
> I don't see how I can decide how errors from ZeroMQ should be handled. Retrying on some error? When? How soon, and how often? In what circumstances? I don't know. What about different platforms?

The same way the Go standard library handles OS errors:

 - EINTR is always retried.
 - API abuse (e.g. sending on a receive-only socket) panics.
 - Other errors are returned.

I will likely fork this repository in the near future to fix this if @pebbe doesn't feel like it.
