### ISSUE TITLE
CPU usage is very high

### ISSUE THREAD

**Issue by GLYASAI** [pebbe/zmq4#172]
Poller uses cgo, which takes up a lot of CPU.

![image](https://user-images.githubusercontent.com/21967570/110426808-adfd7d00-80e1-11eb-9fce-69b8665e5565.png)

[pprof.rainbond-eventlog.samples.cpu.001.pb.gz](https://github.com/pebbe/zmq4/files/6106245/pprof.rainbond-eventlog.samples.cpu.001.pb.gz) is generated by `pprof`

**Comment by pebbe** [comment]
Poll less often

**Comment by GLYASAI** [comment]
Thanks.
