### ISSUE TITLE
Support of cross-compilation?

### ISSUE THREAD

**Issue by herrfz** [pebbe/zmq4#22]
Hi,

It's not an "issue" per se, sorry if it's not appropriate, I just don't know where's the best place to ask this kind of question: I got the following error when cross-compiling my code which uses zmq:

```
[vagrant@localhost coordnode]$ GOARM=7 GOARCH=arm GOOS=linux go build
# github.com/pebbe/zmq4
../../pebbe/zmq4/auth.go:544: undefined: Socket
../../pebbe/zmq4/auth.go:553: undefined: Socket
../../pebbe/zmq4/auth.go:562: undefined: Socket
../../pebbe/zmq4/auth.go:574: undefined: Socket
../../pebbe/zmq4/auth.go:583: undefined: Socket
../../pebbe/zmq4/reactor.go:10: undefined: State
../../pebbe/zmq4/reactor.go:11: undefined: State
```

`Socket` and `State` are variables defined in the package, as far as I understand. So this error is rather weird to me. Any suggestion? Thanks!

**Comment by Jador** [comment]
I made a [docker image] (https://registry.hub.docker.com/u/jador/go-zeromq/) to work around this. Let's you build your app to linux/amd64 from OSX/Windows (if you have something like boot2docker running).

**Comment by gdweijin** [comment]
@Jador thx  I'm learning docker......... :+1:
