### ISSUE TITLE
Create some documentation on how to build for windows

### ISSUE THREAD

**Issue by Hades32** [pebbe/zmq4#3]
Not strictly an "issue" but it would be very helpful to have some documentation on how to get this working on Windows. go get doesn't seem to get the zmq sources and when installing them I didn't get them compiled with mingw64. Precompiled binaries would of course be super cool...

**Comment by marioffmarques** [comment]
Hello,
first of all thanks for your tip Hades. But what you mean by 
- Get the ZeroMQ sources
- in the source folder, go to builds\mingw32 and open a command promt

Which source did you get ? I cant found any source with the builds\mingw32 folder
