### ISSUE TITLE
Can't "go get" due to undefined "getInt" and "getString" in "socketget.go"

### ISSUE THREAD

**Issue by comnik** [pebbe/zmq4#36]
Hey,

I just tried getting the source but go get fails with the following message:

>src/github.com/pebbe/zmq4/socketget.go:428: undefined: getInt
src/github.com/pebbe/zmq4/socketget.go:441: undefined: getString
src/github.com/pebbe/zmq4/socketget.go:453: undefined: getString
src/github.com/pebbe/zmq4/socketget.go:465: undefined: getInt
src/github.com/pebbe/zmq4/socketget.go:495: undefined: getString

I didn't really have the time to investigate, but I think you are calling "getInt" and "getString" instead of "soc.getInt" "soc.getString" in several places.

Thank you for your work!
Niko

**Comment by pebbe** [comment]
Fixed in the last commit.
