### ISSUE TITLE
go install  "could not determine kind of name for C.ZMQ_CURVE_PUBLICKEY "

### ISSUE THREAD

**Issue by wangkechun** [pebbe/zmq4#37]
➜  http-test  go get github.com/pebbe/zmq4
	# github.com/pebbe/zmq4
	could not determine kind of name for C.ZMQ_CURVE_PUBLICKEY
	could not determine kind of name for C.ZMQ_CURVE_SECRETKEY
	could not determine kind of name for C.ZMQ_CURVE_SERVERKEY
	could not determine kind of name for C.ZMQ_GSSAPI_PLAINTEXT
	could not determine kind of name for C.ZMQ_GSSAPI_PRINCIPAL
	could not determine kind of name for C.ZMQ_GSSAPI_SERVER
	could not determine kind of name for C.ZMQ_GSSAPI_SERVICE_PRINCIPAL
	could not determine kind of name for C.ZMQ_HANDSHAKE_IVL
	could not determine kind of name for C.ZMQ_IMMEDIATE
	could not determine kind of name for C.ZMQ_IPV6
	could not determine kind of name for C.ZMQ_LAST_ENDPOINT
	could not determine kind of name for C.ZMQ_MAXMSGSIZE
	could not determine kind of name for C.ZMQ_MECHANISM
	could not determine kind of name for C.ZMQ_MULTICAST_HOPS
	could not determine kind of name for C.ZMQ_PLAIN_PASSWORD
	could not determine kind of name for C.ZMQ_PLAIN_SERVER
	could not determine kind of name for C.ZMQ_PLAIN_USERNAME
	could not determine kind of name for C.ZMQ_RCVHWM
	could not determine kind of name for C.ZMQ_SNDHWM
	could not determine kind of name for C.ZMQ_SOCKS_PROXY
	could not determine kind of name for C.ZMQ_TCP_KEEPALIVE
	could not determine kind of name for C.ZMQ_TCP_KEEPALIVE_CNT
	could not determine kind of name for C.ZMQ_TCP_KEEPALIVE_IDLE
	could not determine kind of name for C.ZMQ_TCP_KEEPALIVE_INTVL
	could not determine kind of name for C.ZMQ_TOS
	could not determine kind of name for C.ZMQ_ZAP_DOMAIN

	➜  http-test  go version
	go version go1.4 linux/amd64

	➜  http-test  gcc -v
	Using built-in specs.
	COLLECT_GCC=gcc
	COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.8/lto-wrapper
	Target: x86_64-linux-gnu
	Configured with: ../src/configure -v --with-pkgversion='Ubuntu 4.8.2-19ubuntu1' --with-bugurl=file:///usr/share/doc/gcc-4.8/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.8 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.8 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-libmudflap --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.8-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
	Thread model: posix
	gcc version 4.8.2 (Ubuntu 4.8.2-19ubuntu1) 

	➜  http-test  uname -a
	Linux wkc-pc 3.13.0-43-generic #72-Ubuntu SMP Mon Dec 8 19:35:06 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

**Comment by pebbe** [comment]
What is this? What is http-test?

**Comment by wangkechun** [comment]
sorry , it is current directory. 
I use oh-my-zsh.

**Comment by pebbe** [comment]
Please try this:

go get -u -v -x github.com/pebbe/zmq4

go env

**Comment by pebbe** [comment]
This error may be because ZeroMQ was built with a different compiler then the one (gcc) you are using for installing zmq4. The solution then would be to install ZeroMQ from source.

**Comment by pebbe** [comment]
Another possibility is that you are using a version of Go that was built with a different compiler. Then you would need to reinstall Go from source.

**Comment by wangkechun** [comment]
➜  ~  go get -u -v -x github.com/pebbe/zmq4
	cd /home/wkc/mygo/src/github.com/pebbe/zmq4
	git remote -v
	github.com/pebbe/zmq4 (download)
	cd /home/wkc/mygo/src/github.com/pebbe/zmq4
	git symbolic-ref HEAD
	cd /home/wkc/mygo/src/github.com/pebbe/zmq4
	git pull --ff-only
	^[[1;7Bcd /home/wkc/mygo/src/github.com/pebbe/zmq4
	git show-ref
	cd /home/wkc/mygo/src/github.com/pebbe/zmq4
	git checkout master
	WORK=/tmp/go-build438273869
	github.com/pebbe/zmq4
	mkdir -p $WORK/github.com/pebbe/zmq4/_obj/
	mkdir -p $WORK/github.com/pebbe/
	cd /home/wkc/mygo/src/github.com/pebbe/zmq4
	pkg-config --cflags libzmq
	pkg-config --libs libzmq
	CGO_LDFLAGS="-g" "-O2" "-lzmq" /home/wkc/Downloads/Downloads/go/pkg/tool/linux_amd64/cgo -objdir $WORK/github.com/pebbe/zmq4/_obj/ -- -I $WORK/github.com/pebbe/zmq4/_obj/ errors.go polling.go socketget.go socketget_unix.go socketset.go zmq4.go
	# github.com/pebbe/zmq4
	could not determine kind of name for C.ZMQ_CURVE_PUBLICKEY
	could not determine kind of name for C.ZMQ_CURVE_SECRETKEY
	could not determine kind of name for C.ZMQ_CURVE_SERVERKEY
	could not determine kind of name for C.ZMQ_GSSAPI_PLAINTEXT
	could not determine kind of name for C.ZMQ_GSSAPI_PRINCIPAL
	could not determine kind of name for C.ZMQ_GSSAPI_SERVER
	could not determine kind of name for C.ZMQ_GSSAPI_SERVICE_PRINCIPAL
	could not determine kind of name for C.ZMQ_HANDSHAKE_IVL
	could not determine kind of name for C.ZMQ_IMMEDIATE
	could not determine kind of name for C.ZMQ_IPV6
	could not determine kind of name for C.ZMQ_LAST_ENDPOINT
	could not determine kind of name for C.ZMQ_MAXMSGSIZE
	could not determine kind of name for C.ZMQ_MECHANISM
	could not determine kind of name for C.ZMQ_MULTICAST_HOPS
	could not determine kind of name for C.ZMQ_PLAIN_PASSWORD
	could not determine kind of name for C.ZMQ_PLAIN_SERVER
	could not determine kind of name for C.ZMQ_PLAIN_USERNAME
	could not determine kind of name for C.ZMQ_RCVHWM
	could not determine kind of name for C.ZMQ_SNDHWM
	could not determine kind of name for C.ZMQ_SOCKS_PROXY
	could not determine kind of name for C.ZMQ_TCP_KEEPALIVE
	could not determine kind of name for C.ZMQ_TCP_KEEPALIVE_CNT
	could not determine kind of name for C.ZMQ_TCP_KEEPALIVE_IDLE
	could not determine kind of name for C.ZMQ_TCP_KEEPALIVE_INTVL
	could not determine kind of name for C.ZMQ_TOS
	could not determine kind of name for C.ZMQ_ZAP_DOMAIN
	➜  ~  go env                               
	GOARCH="amd64"
	GOBIN=""
	GOCHAR="6"
	GOEXE=""
	GOHOSTARCH="amd64"
	GOHOSTOS="linux"
	GOOS="linux"
	GOPATH="/home/wkc/mygo"
	GORACE=""
	GOROOT="/home/wkc/Downloads/Downloads/go"
	GOTOOLDIR="/home/wkc/Downloads/Downloads/go/pkg/tool/linux_amd64"
	CC="gcc"
	GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
	CXX="g++"
	CGO_ENABLED="1"

**Comment by pebbe** [comment]
The output of `get get -x` and `go env` looks good.

What about the suggestion for compiling from source? (Go or ZermoMQ)

**Comment by wangkechun** [comment]
I install zeromq-4.1.0 from source code. and now `go get` seem well.
I originally installed from apt-get.
my os:Ubuntu 14.04.1 LTS
thx.

**Comment by rodrigodmd** [comment]
I had the same issue and the anwer seems to be to specify the right build tag:

`go run -tags zmq_3_x  yourFile.go`

**Comment by thinkhy** [comment]
> I had the same issue and the anwer seems to be to specify the right build tag:
> 
> `go run -tags zmq_3_x yourFile.go`


@rodrigodmd Thanks, you    save my day!

**Comment by nikolas** [comment]
Nevermind, the issue was with my outdated Dockerfile. I was installing `libzmq-dev` instead of `libzmq3-dev`.
