### ISSUE TITLE
unexpected fault address

### ISSUE THREAD

**Issue by gust1n** [pebbe/zmq4#38]
Hi!

I've been using this lib for a while but now for some more complex usage I run into this issue. It's a server that has a DEALER socket that uses the Proxy() function to proxy incoming to a ROUTER socket that has <n> worker REP sockets connected to it, each running in an own goroutine. It all works just fine but for one of my servers I keep getting this error: 
```
unexpected fault address 0x4e49474542
fatal error: fault
[signal 0xb code=0x1 addr=0x4e49474542 pc=0x40162cb]

goroutine 8 [running]:
runtime.gothrow(0x439a760, 0x5)
	/usr/local/Cellar/go/1.4/libexec/src/runtime/panic.go:503 +0x8e fp=0xc2080979a8 sp=0xc208097990
runtime.sigpanic()
	/usr/local/Cellar/go/1.4/libexec/src/runtime/sigpanic_unix.go:29 +0x261 fp=0xc2080979f8 sp=0xc2080979a8
runtime.mallocgc(0x60, 0x42a4140, 0x1, 0x8)
	/usr/local/Cellar/go/1.4/libexec/src/runtime/malloc.go:183 +0x8ab fp=0xc208097aa8 sp=0xc2080979f8
runtime.newarray(0x42a4140, 0x5c, 0x42fade0)
	/usr/local/Cellar/go/1.4/libexec/src/runtime/malloc.go:365 +0xc1 fp=0xc208097ae0 sp=0xc208097aa8
runtime.makeslice(0x4296520, 0x5c, 0x5c, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4/libexec/src/runtime/slice.go:32 +0x15c fp=0xc208097b28 sp=0xc208097ae0
github.com/pebbe/zmq4.(*Socket).RecvBytes(0xc20803d350, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/gust1n/go/src/github.com/pebbe/zmq4/zmq4.go:662 +0x4cf fp=0xc208097c30 sp=0xc208097b28
git.dynamic-design.se/dynamic-cloud/go-butler/butler%2ev2.func·008(0x1)
	[DEDUCTED]/server.go:114 +0x1a3 fp=0xc208097fd8 sp=0xc208097c30
runtime.goexit()
	/usr/local/Cellar/go/1.4/libexec/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc208097fe0 sp=0xc208097fd8
created by [DEDUCTED].(*Server).Start
	[DEDUCTED]/server.go:229 +0x530
```

Has anyone run into this before? Maybe there is a simpler pattern to build an asynchonous server with some running workers?

**Comment by pebbe** [comment]
Are you sure sockets aren't accessed from multiple goroutines? This isn't limited to a direct call on a socket, it could also be something else, like a poller. How do you use the proxy, exactly? The Proxy function itself also accesses the sockets.

Does this always happen in the same function? What is happening in the other threads? Can you trace the problem back to a ZeroMQ library call? Can you repoduce this in a self-contained example?

Try adding runtime.LockOSThread() to the goroutines that use sockets. Does this help?

**Comment by gust1n** [comment]
Hmm I must start off workers in goroutines to get around blocking. The setup today is something like this (error handling omitted):
```go
    sock, _ := ctx.NewSocket(zmq.ROUTER)
    sock.Bind("*:1337")
    
    mux, _ := ctx.NewSocket(zmq.DEALER)
    mux.Bind("inproc://mux")

    go func() {
        worker, _ := ctx.NewSocket(zmq.REP)
        worker.Connect("inproc://mux")
        for {
            b, _ := worker.RecvBytes(0)
            // Handle bytes received (omitted)
        }
    }()

    zmq.Proxy(sock, mux, nil)
```

This setup has worked for me in some applications but now all of a sudden in an application it starts to blow up as stated above. Maybe I'm using the Proxy the wrong way?

**Comment by gust1n** [comment]
And no, setting runtime.LockOSThread() does not help. It does not make a difference if I create one or multiple backing workers either. It's basically the examples/asyncsrv.go but with REP sockets in the worker instead of DEALER. In my e2e test usually 2-3 requests works just fine before it blows...

**Comment by pebbe** [comment]
This looks good. Do you exit the for-loop when worker.RecvBytes(0) returns an error?

Try putting `runtime.LockOSThread()` before the call to zmq.Proxy()

Try running the program after building it with the -race option. Does this print any errors?

There may be some memory corruption caused by another part of the program, and it is detected when Go tries to allocate memory for an array.

**Comment by pebbe** [comment]
I posted a question on the golang group.
https://groups.google.com/forum/#!topic/golang-nuts/gf3vun--pd0

**Comment by gust1n** [comment]
I've tried using the -race flag. I've also tried reproducing using just minimal amount of code but can't seem to do it. Both in my benchmarks and simple e2e scenarios it works just fine. It's when hooking it up to the actual server it crashes.

But it must be some kind of error with concurrent access, cause sometimes it fails after 2 messages, sometimes 3. So it's definitely something colliding somewhere in that timeframe.

**Comment by gust1n** [comment]
And there are only 4 goroutines running: database/sql, glog (flushDaemon), the zmq proxy and the 1 worker rep socket I'm using

**Comment by pebbe** [comment]
Could it be you are linking with a different version of the ZeroMQ library when building the package then  the one that was used when you installed zmq4? If you installed zmq4 with ZeroMQ 4.0, and are now linking with ZeroMQ 4.1, that could explain the memory corruption. The internal storage in libzmq for a message changed from 32 to 48 bytes.

**Comment by gust1n** [comment]
I got my hopes up but it doesn't seem like it unfortunately. I use the latest zeromq from homebrew, 4.0.5 and I manually rebuilt and reinstalled (go get -u github.com/pebbe/zmq4 && go install -a github.com/pebbe/zmq4). There should be no other artifacts? And the only "old" artifacts would still use 4.0.4 which shouldn't have any breaking changes?

**Comment by gust1n** [comment]
Sorry, I did some more in depth testing and it indeed seems like something else is causing the memory corruption. Closing, thanks for helping out!
