### ISSUE TITLE
error: interrupted system call

### ISSUE THREAD

**Issue by gust1n** [pebbe/zmq4#40]
I'm getting really weird behavior using ZMQ and your library. I have a web app that connects to 5 different backing services using 5 different sockers in 5 different contexts. If I put some load on the web app just talking to any of the services the first connection created returns "interrupted system call", (I've check it using ```zmq.Errno(syscall.EINTR)```). 

So basically if a connect (create ctx and socket) on order to service 1,2,3,4,5 and then put a lot of load on service 2, service 1 will receive SIGINT and die. If I reverse it to 5,4,3,2,1 and put a lot of load on service 2, service 5 will crash,

There is nothing in my code (or outside) sending a SIGINT. And regardless how much further I load it, all of the other connections stays up, it's just the very first one created.

Has anyone seen anything like this behavior, sorry if it's not specific to your go implementation.

**Comment by jimenezrick** [comment]
I've seen a few times ZMQ blocking calls being interrupted by the EINTR signal. AFAIK, sometimes this calls are not restarted automatically when seeing this signal and you could do it yourself.

Are you in Linux? Which ZMQ call are you invoking?

**Comment by gust1n** [comment]
This was on OS X but the problem actually went away after reworking the socket connection code so it was probably me that messed up in the first place.
