### ISSUE TITLE
installing problem with C.ZMQ_HWM

### ISSUE THREAD

**Issue by rhacker** [pebbe/zmq4#44]
I have problem getting started with zeromq while getting this package built. After installing libzmq ( latest stable one ) and while getting this one, I have this error : 
```
# github.com/alecthomas/gozmq
could not determine kind of name for C.ZMQ_HWM
could not determine kind of name for C.ZMQ_MCAST_LOOP
could not determine kind of name for C.ZMQ_RECOVERY_IVL_MSEC
could not determine kind of name for C.ZMQ_SWAP
make: *** [deps] Error 2
```

**Comment by pebbe** [comment]
This is not github.com/alecthomas/gozmq

**Comment by rhacker** [comment]
oh I'm sorry ...

**Comment by yaorad** [comment]
sorry if this is not the right place, but is the first search result

the answer is: specify the right build tag (ex: zmq_3_x)
```
go run -tags zmq_3_x  pepito.go
```

**Comment by scil** [comment]
I meet similar erros , because 
```
 sudo apt install libzmq-dev
```
.now i use libzmq3-dev
```
 sudo apt install libzmq3-dev
```
everything works.
