### ISSUE TITLE
Receiving multi-part messages

### ISSUE THREAD

**Issue by rgbkrk** [pebbe/zmq4#52]
How do you receive multi-part messages with this library?

I see documentation on sending multi part, using SendMessage but not the other direction. Am I missing something or does that feature not exist?

**Comment by pebbe** [comment]
RecvMessage

http://godoc.org/github.com/pebbe/zmq4#Socket.RecvMessage

**Comment by rgbkrk** [comment]
Thank you!

I actually figured this out on the plane yesterday and am really happy with it.

Thank you for this excellent implementation/library. :smile:
