### ISSUE TITLE
Static linking fails (due to included C source?)

### ISSUE THREAD

**Issue by binary132** [pebbe/zmq4#56]
I get [**these errors**](
http://pastebin.centos.org/32711/) when I invoke:

`go build --ldflags '-extldflags "-lstdc++ -static -lsodium -static -lzmq"' ./main.go`

> `multiple definition of 'zmq_msg_gets'`
> `github.com/pebbe/zmq4/zmq4.go:31: first defined here`

Note that `zmq4/zmq4.go:31` is [**zmq_msg_gets**](https://github.com/pebbe/zmq4/blob/master/zmq4.go#L29-L31).

How can I statically link this package?  I want to distribute a binary without the shared library dependency.

I've been following the directions here for static linking:
[http://tschottdorf.github.io/linking-golang-go-statically-cgo-testing/](http://tschottdorf.github.io/linking-golang-go-statically-cgo-testing/)

#### Config
 - go1.5 linux/amd64
 - Ubuntu 15.04
 - ZeroMQ 4.1.3 built from source

**Comment by binary132** [comment]
After running `ldconfig`, `go run ./main.go` is giving me:

`panic: zmq4 was installed with ZeroMQ version 4.0.5, but the application links with version 4.1.3`

I'll make sure I have this correct and try again.

**Comment by binary132** [comment]
This was resolved when the correct version of ZeroMQ was installed.

**Comment by bobrik** [comment]
This happened to me when I shared the same built files between different zmq versions. Whenever you change zmq version, you probably want to nuke `$GOPATH/pkg` to let it rebuild.
