### ISSUE TITLE
❓: get message endpoint

### ISSUE THREAD

**Issue by aletheia7** [pebbe/zmq4#62]
Is there a way to receive the endpoint of a message after `router.RecMessage()`?

I have a router socket used in router <-> router communication to connect to multiple endpoints. `router.GetLastEndpoint()` gives the last endpoint of a `router.Connect()`.

`router.RecMessageWithMetadata()` gives nothing.

Perhaps a SocketMonitor() will work, however coordination between to goroutines, one receiving a message and one receiving the SocketMonitor events, may not be possible.

**Comment by pebbe** [comment]
I am not sure what you are asking. 

zmq4 offers what ZeroMQ version 4 is offering. If you need help on how to solve certain design problems, you beter ask on the mailing list.

See: http://zeromq.org/docs:mailing-lists

**Comment by aletheia7** [comment]
I want to get the endpoint (IP address) for each message. Is this available in ZeroMQ?

**Comment by aletheia7** [comment]
Apparently not (2009): http://lists.zeromq.org/pipermail/zeromq-dev/2009-March/000442.html
