### ISSUE TITLE
Zmq4 doesn't throw an error when it can't bind to port

### ISSUE THREAD

**Issue by ckmaresca** [pebbe/zmq4#66]
It seems that zmq4 fails silently when it can't bind to a port because it is already being used.   I was expecting that it would throw an error, but this isn't the case, it just ignores the inability to bind to the specified port with no error.

I will see if I can create a patch for this, but I thought I'd log as an issue first.

**Comment by pebbe** [comment]
Go doesn't throw errors.
If bind fails, it returns an error. You have to check that error.

**Comment by ckmaresca** [comment]
I am checking for an error, no error is generated.  An error should be generated if it fails to bind, that is SOP on every networking stack I have every used in every language.

Not sure why the semantics of 'throw' vs 'return' are such a huge issue with the Go community - they are basically the same thing.  Anyway, sorry for using improper terminology and confusing the issue.

**Comment by ckmaresca** [comment]
Never mind.
