### ISSUE TITLE
Error building with Golang 1.5

### ISSUE THREAD

**Issue by john-oliva** [pebbe/zmq4#67]
I have an application using ZMQ4 which I am attempting to build with Go 1.5. I am receiving the following error: "C source files not allowed when not using cgo or SWIG: dummy.c" which I suppose is due to the fact that Go 1.5 does not include cgo.

How do I get this package to build properly with Go 1.5?

**Comment by pebbe** [comment]
You need cgo. It is part of Go 1.5 too. I don't know why you don't have it. To get cgo to work, you might ask on https://groups.google.com/forum/#!forum/golang-nuts

**Comment by john-oliva** [comment]
Ah, indeed it was a cockpit error on my part.  My build script was including CGO_ENABLED=0 so cgo was not running.
