### ISSUE TITLE
Tests for STREAM

### ISSUE THREAD

**Issue by lancecarlson** [pebbe/zmq4#70]
Is there anyway you can replicate this example and get it to work?

http://api.zeromq.org/4-0:zmq-socket#toc19

Receiving messages works fine, but sending does nothing. Any ideas?

https://gist.github.com/lancecarlson/36a3b4cdbe9825ba161d

Visiting http://localhost:8080 hangs, but I'm able to print the http request.

**Comment by pebbe** [comment]
This isn't right:

    `HTTP/1.0 200 OK\r\n`

With backtics, the \r\n are just four bytes

**Comment by lancecarlson** [comment]
OK, I just tried with " and it still didn't work. Also with curl, it just hangs:

$ PORT=8080 go run http.go
RECEIVING
[?A? GET / HTTP/1.1
Host: localhost:8080
User-Agent: curl/7.43.0
Accept: */*

]

$ curl -vv http://localhost:8080/
*   Trying ::1...
* connect to ::1 port 8080 failed: Connection refused
*   Trying fe80::1...
* connect to fe80::1 port 8080 failed: Connection refused
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET / HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.43.0
> Accept: */*
>

**Comment by lancecarlson** [comment]
Modified gist to only have double quotes

**Comment by pebbe** [comment]
Did you try the C version. Does that work?

**Comment by lancecarlson** [comment]
Yep, it works.

https://gist.github.com/lancecarlson/fb0cfd0354005098d579

Ran using 

```sh
clang -Wall http.c -o http -L/usr/local/Cellar/zeromq/4.0.5_2/lib/ -lzmq && ./http
```

opened my browser and it said Hello World

**Comment by pebbe** [comment]
You don't do any error checking. With error checks, I found what was wrong very easily.

In Go you send one return frame where the C code returns four.

Adding error check in the C code reveils it isn't working quite allright either. It responds to single frames, but requests are two frames, the first the sender id, the second an empty frame. 

Working Go code:
```go
package main

import (
	"fmt"
	"log"
	"os"

	zmq "github.com/pebbe/zmq4"
)

var (
	httpPort string
)

func init() {
	httpPort = os.Getenv("PORT")
	if httpPort == "" {
		log.Fatal("PORT required")
	}
}

func main() {
	stream, err := zmq.NewSocket(zmq.STREAM)
	if err != nil {
		panic(err)
	}
	defer stream.Close()
	err = stream.Bind("tcp://*:" + httpPort)
	if err != nil {
		panic(err)
	}

	for {
		fmt.Println("RECEIVING")
		msg, err := stream.RecvMessage(0)
		if err != nil {
			panic(err)
		}
		fmt.Printf("%q\n", msg)
		res := fmt.Sprintf("HTTP/1.0 200 OK\r\n"+
			"Content-Type: text/plain\r\n"+
			"\r\n"+
			"Hello, World! %q\r\n", msg)
		fmt.Println("SENDING")
		_, err = stream.Send(msg[0], zmq.SNDMORE)
		if err != nil {
			panic(err)
		}
		_, err = stream.Send(res, zmq.SNDMORE)
		if err != nil {
			panic(err)
		}
		_, err = stream.Send(msg[0], zmq.SNDMORE)
		if err != nil {
			panic(err)
		}
		_, err = stream.Send("", zmq.SNDMORE)
		if err != nil {
			panic(err)
		}
	}
}
```
C code with error checks:
```c

#include <zmq.h>
#include <string.h>
#include <assert.h>

int main() {

    void *ctx = zmq_ctx_new ();
    assert (ctx);
    /* Create ZMQ_STREAM socket */
    void *socket = zmq_socket (ctx, ZMQ_STREAM);
    assert (socket);
    int rc = zmq_bind (socket, "tcp://*:8080");
    assert (rc == 0);
    /* Data structure to hold the ZMQ_STREAM ID */
    uint8_t id [256];
    size_t id_size = 256;
    while (1) {
	/* Get HTTP request; ID frame and then request */
	id_size = zmq_recv (socket, id, 256, 0);
	assert (id_size > 0);
	/* Prepares the response */
	char http_response [] =
	    "HTTP/1.0 200 OK\r\n"
	    "Content-Type: text/plain\r\n"
	    "\r\n"
	    "Hello, World!\r\n";
	/* Sends the ID frame followed by the response */
	rc = zmq_send (socket, id, id_size, ZMQ_SNDMORE);
	if (rc < 0)
	    printf("%s\n", zmq_strerror(zmq_errno()));
	else
	    printf("bytes: %i\n", rc);
	rc = zmq_send (socket, http_response, strlen (http_response), ZMQ_SNDMORE);
	if (rc < 0)
	    printf("%s\n", zmq_strerror(zmq_errno()));
	else
	    printf("bytes: %i\n", rc);

	/* Closes the connection by sending the ID frame followed by a zero response */
	rc = zmq_send (socket, id, id_size, ZMQ_SNDMORE);
	if (rc < 0)
	    printf("%s\n", zmq_strerror(zmq_errno()));
	else
	    printf("bytes: %i\n", rc);

	rc = zmq_send (socket, 0, 0, ZMQ_SNDMORE);
	if (rc < 0)
	    printf("%s\n", zmq_strerror(zmq_errno()));
	else
	    printf("bytes: %i\n", rc);

	/* NOTE: If we don't use ZMQ_SNDMORE, then we won't be able to send more */
	/* message to any client */
    }
    zmq_close (socket); zmq_ctx_destroy (ctx);
    return 0;
}
```

**Comment by lancecarlson** [comment]
Ah very nice! Thanks! I was more concerned with the Go version. C version was on the 0mq site. Do you think this example would be useful to have in the examples folder somewhere? It was helpful for me

**Comment by pebbe** [comment]
I think it is too simple for that. And the examples folder is for examples from the tutorial only.
