### ISSUE TITLE
Add SetFd()

### ISSUE THREAD

**Issue by aletheia7** [pebbe/zmq4#88]
Can you add Socket.SetFd() to support [zmq_setsockopt(ZMQ_PRE_ALLOCATED_FD)](https://github.com/zeromq/libzmq/commit/4bcbb3055ebf6753a2135fb3132311603d6ea930).This socket option was added to https://github.com/zeromq/libzmq/commit/4bcbb3055ebf6753a2135fb3132311603d6ea930. I would like to use [Linux systemd Socket Activation](http://0pointer.de/blog/projects/socket-activation.html) instead of Socket.Bind().

**Comment by pebbe** [comment]
This option is not currently in the master branch of ZeroMQ, so I guess it has been removed again, or renamed. There is a `ZMQ_USE_FD`. Is that what you want?

**Comment by pebbe** [comment]
Added functions `GetUseFd` and `SetUseFd` in branch `devel`.

Subject to change. This will not be merged into margin until the official release of ZeroMQ version 4.2.

**Comment by aletheia7** [comment]
Thank you.
