### ISSUE TITLE
rr client/worker example incorrect.

### ISSUE THREAD

**Issue by laszlo-kiss** [pebbe/zmq4#93]
The worker should be using `responder.bind()` instead of `responder.connect()`. The two are also using different ports which makes no sense.

**Comment by pebbe** [comment]
The example is correct.

See http://zguide.zeromq.org/page:all#Shared-Queue-DEALER-and-ROUTER-sockets

**Comment by laszlo-kiss** [comment]
Sorry about that. I missed the whole dealer/router thing.
