### ISSUE TITLE
program compiled on mac 10.12.4 will be killed

### ISSUE THREAD

**Issue by shengdoushi** [pebbe/zmq4#99]
on mac 10.12.4, compiled ok, but run crash:
➜  gotest export GOPATH=/tmp/gotest  && cd /tmp/gotest
➜  gotest go get github.com/pebbe/zmq4
➜  gotest cat src/gotest/main.go
package main

import (
	"fmt"

	_ "github.com/pebbe/zmq4"
)

func main(){
	fmt.Println("ok")
}

➜  gotest go build gotest && ./gotest
[1]    40809 killed     ./gotest

-----------------------------------------------------------------------
go env:

GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/tmp/gotest"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.8/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.8/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/z4/wy11nkv92_d_0b26pt89r1600000gn/T/go-build901313084=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"

**Comment by aletheia7** [comment]
Many people are having go programs crash on OSX 10.12.4.

See [runtime: some Go executables broken with macOS 10.12.4 / Xcode 8.3 but fine with Xcode 8.2](https://github.com/golang/go/issues/19734?utm_source=golangweekly&utm_medium=email)

**Comment by pebbe** [comment]
So it looks like this is unrelated to zmq4. I will close this issue.
